name: webview_flutter_platform_interface
description: A common platform interface for the webview_flutter plugin.
# NOTE: We strongly prefer non-breaking changes, even at the expense of a
# less-clean API. See https://flutter.dev/go/platform-interface-breaking-changes
version: 1.8.0

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.22.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface:
    git:
      url: https://github.com/ankit-roy-greenway/plugin_platform_interface.git
      ref: main

dev_dependencies:
  pedantic: ^1.9.2
